---
- name: Update apt packages
  become: true
  become_method: sudo
  apt:
    update_cache: yes

- name: upgrade packages
  become: true
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: Install NodeJs, NPM
  become: true
  apt: 
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: Install PM2
  become: true
  npm:
    name: pm2
    global: yes
    state: present
    production: yes

- name: Create Web directory
  file:
    path: ~/web
    state: directory

- name: Copy index.js file
  copy:
    src: files/index.js
    dest: ~/web/index.js

- name: Start web server
  become: true
  shell:
    cmd: pm2 start ~/web/index.js -f